---
fail_fast: true

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

ci:
  # We use system Python, with required dependencies specified in pyproject.toml.
  # We therefore cannot use those dependencies in pre-commit CI.
  skip:
    - actionlint
    - doc8
    - pyproject-fmt-fix
    - shellcheck
    - sphinx-lint
    - yamlfix
    - zizmor

# This should match the hook stages run in the lint configuration.
default_install_hook_types: [pre-commit]

repos:
  - repo: meta
    hooks:
      - id: check-useless-excludes
        stages: [pre-commit]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        stages: [pre-commit]
      - id: check-case-conflict
        stages: [pre-commit]
      - id: check-executables-have-shebangs
        stages: [pre-commit]
      - id: check-merge-conflict
        stages: [pre-commit]
      - id: check-shebang-scripts-are-executable
        stages: [pre-commit]
      - id: check-symlinks
        stages: [pre-commit]
      - id: check-json
        stages: [pre-commit]
      - id: check-toml
        stages: [pre-commit]
      - id: check-vcs-permalinks
        stages: [pre-commit]
      - id: check-yaml
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: file-contents-sorter
        files: spelling_private_dict\.txt$
        stages: [pre-commit]
      - id: trailing-whitespace
        stages: [pre-commit]
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: rst-directive-colons
        stages: [pre-commit]
      - id: rst-inline-touching-normal
        stages: [pre-commit]
      - id: text-unicode-replacement-char
        stages: [pre-commit]
      - id: rst-backticks
        stages: [pre-commit]
  - repo: local
    hooks:
      - id: actionlint
        name: actionlint
        entry: uv run --extra=dev actionlint
        language: python
        pass_filenames: false
        types_or: [yaml]
        additional_dependencies: [uv==0.9.5]
        stages: [pre-commit]

      - id: shellcheck
        name: shellcheck
        entry: uv run --extra=dev shellcheck --shell=bash
        language: python
        types_or: [shell]
        additional_dependencies: [uv==0.9.5]
        stages: [pre-commit]

      - id: doc8
        name: doc8
        entry: uv run --extra=dev -m doc8
        language: python
        types_or: [rst]
        additional_dependencies: [uv==0.9.5]
        stages: [pre-commit]

      - id: pyproject-fmt-fix
        name: pyproject-fmt
        entry: uv run --extra=dev pyproject-fmt
        language: python
        types_or: [toml]
        files: pyproject.toml
        additional_dependencies: [uv==0.9.5]
        stages: [pre-commit]

      - id: yamlfix
        name: yamlfix
        entry: uv run --extra=dev yamlfix
        language: python
        types_or: [yaml]
        additional_dependencies: [uv==0.9.5]
        stages: [pre-commit]

      - id: zizmor
        name: zizmor
        entry: uv run --extra=dev zizmor --strict-collection .github
        language: python
        pass_filenames: false
        types_or: [yaml]
        additional_dependencies: [uv==0.9.5]
        stages: [pre-commit]

      - id: sphinx-lint
        name: sphinx-lint
        entry: uv run --extra=dev sphinx-lint --enable=all --disable=line-too-long
        language: python
        types_or: [rst]
        additional_dependencies: [uv==0.9.5]
        stages: [pre-commit]
